# This is a basic workflow to help you get started with Actions

name: Basic Startup

# Controls when the workflow will run
on:
 push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04
    container:
      image: debian:latest 
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install needed packages
        run: apt update && apt install git debootstrap -y
