# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04
    container:
      image: debian:unstable 
      volumes:
        - /proc:/proc
        - /:/run/host
      options: --privileged -it
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install needed packages
        run: apt update && apt install git debootstrap -y

      # Runs a set of commands using the runners shell
      - name: ISO Building
        run: | 
          cd /
          git clone https://github.com/LED-esma/iso-builder-devel
          cd iso-builder-devel
          ./build.sh etc/terraform.conf
        
      - uses: actions/upload-artifact@v3
        with:
         name: Debian
         path: /iso-builder-devel/builds
